#!/bin/bash
if [ -z "$PYFILE" ]; then
	echo "The PYFILE environement variable is not set."
	exit 1
fi
python3 -m py_compile "$PYFILE"
{$PYFILE}c
compiled_file="${PYFILE}c"
mv "__pycache__/$
{PYFILE%.py}.cpython-*.pyc"
"$compiled_file"
rmdir "__pycache__"
